Automated documentation creation&publishing to GH-pages
PinguDevTeam/ICF-MI-framework pull request #35
Opened 2022-11-29 14:02 UTC by dorukaks

## Purpose
Create GitHub actions to automatically create documentation of the pipeline and publish the created documentation on GitHub pages.

_Tag each of the issues that you are addressing with this PR with "Closes #<issueNumber>"_
Closes #31 

- Automate the documentation pipeline
- Publish documentation to GitHub pages

## Type of change
_What types of change is it?_
_Select the appropriate type(s) that describe this PR_

- New feature (non-breaking change which adds functionality)
- Repository chores (changes made to improve repository/workflow quality)
- Documentation update

## Checklist
_Put an `x` in the boxes that apply._

- [ ] My code functions as intended
- [ ] I have used camelCase in my variable and function names
- [ ] I have commented my code properly
- [ ] I have provided the necessary prompts for automatic documentation
- [ ] I have provided a toy case under the examples folder
- [ ] I have addressed all the issues entirely

2022-11-29 17:30 UTC, dorukaks commented
http://kicktv.tumblr.com/post/31814804688/emotion

2022-11-29 17:31 UTC, dorukaks commented
![image](https://user-images.githubusercontent.com/52582668/204600691-95998fb8-b354-4892-8dd6-5d2bedb23906.png)

2022-11-29 17:56 UTC, dorukaks commented
@sahilbhola14 need you to have a look to confirm the behavior of the github pages, if it's producing expected behavior, we can mark this as ready to review :+1:

2022-11-29 18:06 UTC, sahilbhola14 commented
Great job @dorukaks.
It seems the modules are missing, i.e. the main code-base is not being documented

2022-11-29 19:32 UTC, dorukaks commented
> Great job @dorukaks. It seems the modules are missing, i.e. the main code-base is not being documented

is it normally getting created when you run it locally?

2022-11-30 06:05 UTC, sahilbhola14 commented
Alright Alright Alright! It's working

2022-11-30 06:09 UTC, sahilbhola14 commented
CAUTION: Since this PR has a lot of commits, it might be more suitable to `squash` while doing the merge. Let me know if help is needed :)

2022-11-30 06:11 UTC, sahilbhola14 commented
@dorukaks Lets merge this to main only and then freeze main. Update the dev and then start working?

2022-11-30 12:09 UTC, dorukaks commented
> Alright Alright Alright! It's working

![](https://media.giphy.com/media/huJmPXfeir5JlpPAx0/giphy.gif)

2022-11-30 12:50 UTC, dorukaks commented
> @dorukaks Lets merge this to main only and then freeze main. Update the `dev` and then start working?

Allright! Once we get approvals from @camckenn @cfkawa, I'll perform a squash merge and then lock main

2022-11-30 13:01 UTC, cfkawa approved these changes

2022-11-30 22:19 UTC, sahilbhola14 requested changes

2022-11-30 22:19 UTC, sahilbhola14 commented on docs/conf.py
> +sys.path.insert(0, os.path.abspath("../src/"))
I am not sure why was this added?

2022-11-30 22:19 UTC, sahilbhola14 commented on src/TTICE/__init__.py
> +def testFcn(a):
@dorukaks do you wanna add this test function as part of this PR?

2022-11-30 22:22 UTC, dorukaks commented on src/TTICE/__init__.py
> +def testFcn(a):
It's a placeholder function i created to test the output of automatic documentation actions. It will be overwritten by my changes in #34.

2022-11-30 22:23 UTC, dorukaks commented on docs/conf.py
> +sys.path.insert(0, os.path.abspath("../src/"))
I added this to understand how the output is getting created on GitHub pages. You can delete any lines as you see fit

2022-11-30 23:01 UTC, sahilbhola14 commented on src/TTICE/__init__.py
> +def testFcn(a):
Can we move to #34, or will have some conflicts? As this PR will just automate the documentation.

2022-11-30 23:08 UTC, dorukaks commented on src/TTICE/__init__.py
> +def testFcn(a):
there won't be any conflicts as it's not in `main` or `dev`, you can revert all files in TTICE subdirectory to their version in `main`, shouldn't cause any issues :+1:

2022-12-01 18:21 UTC, camckenn approved these changes

2022-12-02 17:21 UTC, dorukaks commented
@sahilbhola14 I pruned @cfkawa's branches and re-run the build job, currently the [documentation page](https://pingudevteam.github.io/ICF-MI-framework/index.html) looks functional. If you confirm this, we can merge to main and freeze main.

2022-12-04 04:28 UTC, sahilbhola14 commented
> @sahilbhola14 I pruned @cfkawa's branches and re-run the build job, currently the [documentation page](https://pingudevteam.github.io/ICF-MI-framework/index.html) looks functional. If you confirm this, we can merge to main and freeze main.

@dorukaks seems like it's working, we can close the PR

2022-12-04 08:26 UTC, sahilbhola14 approved these changes

2022-12-04 08:27 UTC, merged